version: '3.8'
services:


  client-backend:
    container_name: maco
    image: client:0.0.1
#    build:
#      context: ..
#      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      service-db:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8181/
      interval: 1h
      timeout: 5s
      retries: 10
      start_period: 2m
      start_interval: 5s
    networks:
      - network-maco
    environment:
      - SERVER_PORT=8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db:5432/maconconsulting_library
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  service-db:
    container_name: service-db
    image: postgres:17
    restart: on-failure
    ports:
      - "15432:5432"
    volumes:
      - ./docker/data:/var/lib/postgresql/data
      - ./docker/ddl:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - network-maco
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U postgres"]
      interval: 1h
      timeout: 5s
      retries: 10
      start_period: 20s
      start_interval: 5s

networks:
  network-maco:

#  pgadmin
#  container_name: pgadmin4_container
#  image: dpage/pgadmin4:7
#  restart: always
#  environment:
#    PGADMIN_DEFAULT_EMAIL: admin@admin.com
#    PGADMIN_DEFAULT_PASSWORD: root
#  ports:
#    - "5050:80"
#  volumes:
#    - pgadmin-data:/var/lib/pgadmin

#volumes:
#  db-data:
#  pgadmin-data: