CREATE TABLE macon_user (
    id         int       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp DEFAULT now() NOT NULL,
    name       varchar   NOT NULL,
    login      varchar   NOT NULL UNIQUE,
    email      varchar   NOT NULL UNIQUE,
    password   varchar   NOT NULL,
    role       varchar   NOT NULL
);

CREATE TABLE type (
    id         int       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp DEFAULT now() NOT NULL,
    name       varchar   NOT NULL
);

CREATE TABLE segment (
    id         int       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp DEFAULT now() NOT NULL,
    name       varchar   NOT NULL
);

CREATE TABLE format (
    id         int       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp DEFAULT now() NOT NULL,
    name       varchar   NOT NULL
);

CREATE TABLE project (
    id          int       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp DEFAULT now() NOT NULL,
    year        int       NOT NULL,
    relevance   varchar,
    title       varchar   NOT NULL UNIQUE,
    client      varchar,
    location    varchar   NOT NULL,
    key_words   varchar,
    methodology varchar
);

CREATE TABLE project_type (
    project_id int REFERENCES project(id),
    type_id int REFERENCES type(id),
    PRIMARY KEY (project_id, type_id)
);

CREATE TABLE project_segment (
    project_id int REFERENCES project(id),
    segment_id int REFERENCES segment(id),
    PRIMARY KEY (project_id, segment_id)
);

CREATE TABLE project_format (
    project_id int REFERENCES project(id),
    format_id  int REFERENCES format(id),
    PRIMARY KEY (project_id, format_id)
);

CREATE TABLE type_of_publication (
    id         int       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp DEFAULT now() NOT NULL,
    name       varchar   NOT NULL
);

CREATE TABLE publication (
    id                    int       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at            timestamp DEFAULT now() NOT NULL,
    title                 varchar   NOT NULL UNIQUE,
    related_project_title varchar,
    annotation            varchar,
    source                varchar,
    year                  int,
    relevance             varchar,
    path                  varchar,
    location              varchar
);

CREATE TABLE publication_segment (
    publication_id int REFERENCES publication(id),
    segment_id     int REFERENCES segment(id),
    PRIMARY KEY (publication_id, segment_id)
);

CREATE TABLE publication_format (
    publication_id int REFERENCES publication(id),
    format_id      int REFERENCES format(id),
    PRIMARY KEY (publication_id, format_id)
);

CREATE TABLE publication_type (
    publication_id         int REFERENCES publication(id),
    type_of_publication_id int REFERENCES type_of_publication(id),
    PRIMARY KEY (publication_id, type_of_publication_id)
);